all:
	cmake CMakeLists.txt
	make
	rm Makefile
	cp makef/Makefile .
	./chess_wibget

go:
	./chess_wibget

clean:
	rm -rf CMakeLists.txt.user
	rm -rf cmake_install.cmake
	rm -rf CMakeCache.txt
	rm -rf chess_wibget_autogen
	rm -rf CMakeFiles
	rm -rf chess_wibget
